# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'spider_UI_layout.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

# import spider_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1164, 778)
        icon = QIcon()
        icon.addFile(u":/Spider/spider.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionclose = QAction(MainWindow)
        self.actionclose.setObjectName(u"actionclose")
        font = QFont()
        font.setFamily(u"Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.actionclose.setFont(font)
        self.actionsave = QAction(MainWindow)
        self.actionsave.setObjectName(u"actionsave")
        self.actionsave.setFont(font)
        self.actionwumaomao = QAction(MainWindow)
        self.actionwumaomao.setObjectName(u"actionwumaomao")
        self.actionwumaomao.setFont(font)
        self.actionauthor = QAction(MainWindow)
        self.actionauthor.setObjectName(u"actionauthor")
        self.actionauthor.setCheckable(True)
        self.actionauthor.setChecked(True)
        self.actiongenre = QAction(MainWindow)
        self.actiongenre.setObjectName(u"actiongenre")
        self.actiongenre.setCheckable(True)
        self.actiongenre.setChecked(True)
        self.actionstatus = QAction(MainWindow)
        self.actionstatus.setObjectName(u"actionstatus")
        self.actionstatus.setCheckable(True)
        self.actionstatus.setChecked(True)
        self.actionname = QAction(MainWindow)
        self.actionname.setObjectName(u"actionname")
        self.actionname.setCheckable(True)
        self.actionname.setChecked(True)
        self.actionupdate_chapter = QAction(MainWindow)
        self.actionupdate_chapter.setObjectName(u"actionupdate_chapter")
        self.actionupdate_chapter.setCheckable(True)
        self.actionupdate_chapter.setChecked(False)
        self.actionintro = QAction(MainWindow)
        self.actionintro.setObjectName(u"actionintro")
        self.actionintro.setCheckable(True)
        self.actionintro.setChecked(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(30, 10, 1001, 761))
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setFamily(u"Microsoft YaHei UI")
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setWeight(75)
        self.tabWidget_2.setFont(font1)
        self.tabWidget_2.setMovable(True)
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.gridLayout = QGridLayout(self.tab_3)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.tab_3)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy1)
        self.tabWidget.setFont(font1)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"background-color: rgb(255, 255, 238);")
        self.tabWidget.setMovable(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(71, 161, 54, 22))
        sizePolicy1.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy1)
        self.label_2.setFont(font1)
        self.state_label = QLabel(self.tab)
        self.state_label.setObjectName(u"state_label")
        self.state_label.setGeometry(QRect(131, 161, 691, 22))
        sizePolicy1.setHeightForWidth(self.state_label.sizePolicy().hasHeightForWidth())
        self.state_label.setSizePolicy(sizePolicy1)
        self.state_label.setFont(font1)
        self.state_label.setScaledContents(True)
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(70, 240, 55, 22))
        sizePolicy1.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy1)
        self.label.setFont(font1)
        self.book_list = QListWidget(self.tab)
        self.book_list.setObjectName(u"book_list")
        self.book_list.setGeometry(QRect(130, 270, 256, 351))
        sizePolicy1.setHeightForWidth(self.book_list.sizePolicy().hasHeightForWidth())
        self.book_list.setSizePolicy(sizePolicy1)
        self.book_list.setFont(font1)
        self.book_list.setAutoFillBackground(True)
        self.book_list.setResizeMode(QListView.Fixed)
        self.book_list.setLayoutMode(QListView.Batched)
        self.book_list.setWordWrap(True)
        self.progressbar = QProgressBar(self.tab)
        self.progressbar.setObjectName(u"progressbar")
        self.progressbar.setGeometry(QRect(130, 190, 321, 30))
        sizePolicy1.setHeightForWidth(self.progressbar.sizePolicy().hasHeightForWidth())
        self.progressbar.setSizePolicy(sizePolicy1)
        self.progressbar.setFont(font1)
        self.progressbar.setValue(0)
        self.progressbar.setInvertedAppearance(False)
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(750, 70, 71, 51))
        sizePolicy1.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy1)
        self.label_8.setFont(font1)
        self.label_8.setStyleSheet(u"image: url(:/Spider/novel_spider.svg);")
        self.search_push_button = QPushButton(self.tab)
        self.search_push_button.setObjectName(u"search_push_button")
        self.search_push_button.setGeometry(QRect(630, 110, 75, 28))
        sizePolicy1.setHeightForWidth(self.search_push_button.sizePolicy().hasHeightForWidth())
        self.search_push_button.setSizePolicy(sizePolicy1)
        self.search_push_button.setFont(font1)
        self.layoutWidget = QWidget(self.tab)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(61, 111, 267, 28))
        sizePolicy1.setHeightForWidth(self.layoutWidget.sizePolicy().hasHeightForWidth())
        self.layoutWidget.setSizePolicy(sizePolicy1)
        self.layoutWidget.setFont(font1)
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.book_name_label = QLabel(self.layoutWidget)
        self.book_name_label.setObjectName(u"book_name_label")
        sizePolicy1.setHeightForWidth(self.book_name_label.sizePolicy().hasHeightForWidth())
        self.book_name_label.setSizePolicy(sizePolicy1)
        self.book_name_label.setFont(font1)

        self.horizontalLayout_3.addWidget(self.book_name_label)

        self.book_name = QLineEdit(self.layoutWidget)
        self.book_name.setObjectName(u"book_name")
        sizePolicy1.setHeightForWidth(self.book_name.sizePolicy().hasHeightForWidth())
        self.book_name.setSizePolicy(sizePolicy1)
        self.book_name.setFont(font1)

        self.horizontalLayout_3.addWidget(self.book_name)

        self.book_source_combobox = QComboBox(self.tab)
        self.book_source_combobox.addItem("")
        self.book_source_combobox.addItem("")
        self.book_source_combobox.addItem("")
        self.book_source_combobox.setObjectName(u"book_source_combobox")
        self.book_source_combobox.setGeometry(QRect(430, 110, 121, 41))
        sizePolicy1.setHeightForWidth(self.book_source_combobox.sizePolicy().hasHeightForWidth())
        self.book_source_combobox.setSizePolicy(sizePolicy1)
        self.book_source_combobox.setFont(font1)
        self.source_label = QLabel(self.tab)
        self.source_label.setObjectName(u"source_label")
        self.source_label.setGeometry(QRect(350, 120, 63, 19))
        sizePolicy1.setHeightForWidth(self.source_label.sizePolicy().hasHeightForWidth())
        self.source_label.setSizePolicy(sizePolicy1)
        self.source_label.setFont(font1)
        self.exit_novel_list = QListWidget(self.tab)
        self.exit_novel_list.setObjectName(u"exit_novel_list")
        self.exit_novel_list.setGeometry(QRect(450, 230, 256, 401))
        sizePolicy1.setHeightForWidth(self.exit_novel_list.sizePolicy().hasHeightForWidth())
        self.exit_novel_list.setSizePolicy(sizePolicy1)
        self.exit_novel_list.setFont(font1)
        self.exit_novel_list.setMouseTracking(True)
        self.novel_status_list = QListWidget(self.tab)
        self.novel_status_list.setObjectName(u"novel_status_list")
        self.novel_status_list.setGeometry(QRect(730, 230, 111, 401))
        sizePolicy1.setHeightForWidth(self.novel_status_list.sizePolicy().hasHeightForWidth())
        self.novel_status_list.setSizePolicy(sizePolicy1)
        self.novel_status_list.setFont(font1)
        self.novel_status_list.setMouseTracking(True)
        self.novel_status_list.setResizeMode(QListView.Adjust)
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(460, 200, 241, 21))
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(730, 200, 91, 21))
        sizePolicy1.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy1)
        self.label_6.setFont(font1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.horizontalLayoutWidget = QWidget(self.tab_2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(62, 130, 681, 471))
        self.horizontalLayoutWidget.setFont(font1)
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.rank_book_name_list = QListWidget(self.horizontalLayoutWidget)
        self.rank_book_name_list.setObjectName(u"rank_book_name_list")
        self.rank_book_name_list.setFont(font1)
        self.rank_book_name_list.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.rank_book_name_list.setMovement(QListView.Free)
        self.rank_book_name_list.setResizeMode(QListView.Adjust)
        self.rank_book_name_list.setLayoutMode(QListView.SinglePass)
        self.rank_book_name_list.setUniformItemSizes(True)

        self.horizontalLayout.addWidget(self.rank_book_name_list)

        self.rank_author_list = QListWidget(self.horizontalLayoutWidget)
        self.rank_author_list.setObjectName(u"rank_author_list")
        self.rank_author_list.setMaximumSize(QSize(108, 469))
        self.rank_author_list.setFont(font1)
        self.rank_author_list.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.rank_author_list.setMovement(QListView.Free)
        self.rank_author_list.setResizeMode(QListView.Adjust)
        self.rank_author_list.setUniformItemSizes(True)

        self.horizontalLayout.addWidget(self.rank_author_list)

        self.rank_genre_list = QListWidget(self.horizontalLayoutWidget)
        self.rank_genre_list.setObjectName(u"rank_genre_list")
        self.rank_genre_list.setMaximumSize(QSize(115, 469))
        self.rank_genre_list.setFont(font1)
        self.rank_genre_list.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.rank_genre_list.setMovement(QListView.Free)
        self.rank_genre_list.setResizeMode(QListView.Adjust)
        self.rank_genre_list.setUniformItemSizes(True)

        self.horizontalLayout.addWidget(self.rank_genre_list)

        self.rank_status_list = QListWidget(self.horizontalLayoutWidget)
        self.rank_status_list.setObjectName(u"rank_status_list")
        self.rank_status_list.setMaximumSize(QSize(122, 469))
        self.rank_status_list.setFont(font1)
        self.rank_status_list.setMouseTracking(True)
        self.rank_status_list.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.rank_status_list.setMovement(QListView.Snap)
        self.rank_status_list.setResizeMode(QListView.Adjust)
        self.rank_status_list.setUniformItemSizes(True)

        self.horizontalLayout.addWidget(self.rank_status_list)

        self.rank_intro_list = QListWidget(self.horizontalLayoutWidget)
        self.rank_intro_list.setObjectName(u"rank_intro_list")
        self.rank_intro_list.setFont(font1)
        self.rank_intro_list.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.rank_intro_list.setMovement(QListView.Free)
        self.rank_intro_list.setResizeMode(QListView.Adjust)
        self.rank_intro_list.setUniformItemSizes(True)

        self.horizontalLayout.addWidget(self.rank_intro_list)

        self.rank_newest_chapter_list = QListWidget(self.horizontalLayoutWidget)
        self.rank_newest_chapter_list.setObjectName(u"rank_newest_chapter_list")
        self.rank_newest_chapter_list.setMinimumSize(QSize(127, 0))
        self.rank_newest_chapter_list.setFont(font1)
        self.rank_newest_chapter_list.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.rank_newest_chapter_list.setMovement(QListView.Free)
        self.rank_newest_chapter_list.setResizeMode(QListView.Adjust)
        self.rank_newest_chapter_list.setUniformItemSizes(True)

        self.horizontalLayout.addWidget(self.rank_newest_chapter_list)

        self.gridLayoutWidget = QWidget(self.tab_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(140, 40, 511, 80))
        self.gridLayoutWidget.setFont(font1)
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.rank_label = QLabel(self.gridLayoutWidget)
        self.rank_label.setObjectName(u"rank_label")
        self.rank_label.setFont(font1)

        self.gridLayout_2.addWidget(self.rank_label, 1, 0, 1, 1)

        self.source_cobox = QComboBox(self.gridLayoutWidget)
        self.source_cobox.addItem("")
        self.source_cobox.setObjectName(u"source_cobox")
        font2 = QFont()
        font2.setFamily(u"Microsoft YaHei UI")
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setWeight(75)
        self.source_cobox.setFont(font2)

        self.gridLayout_2.addWidget(self.source_cobox, 1, 1, 1, 1)

        self.rank_button = QPushButton(self.gridLayoutWidget)
        self.rank_button.setObjectName(u"rank_button")
        self.rank_button.setFont(font1)

        self.gridLayout_2.addWidget(self.rank_button, 1, 2, 1, 1)

        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(660, 50, 71, 51))
        self.label_9.setFont(font1)
        self.label_9.setStyleSheet(u"image: url(:/Spider/novel_spider.svg);")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.textBrowser = QTextBrowser(self.tab_5)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 0, 961, 621))
        font3 = QFont()
        font3.setFamily(u"Microsoft YaHei UI")
        font3.setPointSize(14)
        self.textBrowser.setFont(font3)
        self.textBrowser.setAutoFormatting(QTextEdit.AutoAll)
        self.preview_button = QPushButton(self.tab_5)
        self.preview_button.setObjectName(u"preview_button")
        self.preview_button.setGeometry(QRect(44, 622, 91, 31))
        self.preview_button.setFont(font1)
        self.Next_button = QPushButton(self.tab_5)
        self.Next_button.setObjectName(u"Next_button")
        self.Next_button.setGeometry(QRect(794, 622, 91, 31))
        self.Next_button.setFont(font1)
        self.Menu_button = QPushButton(self.tab_5)
        self.Menu_button.setObjectName(u"Menu_button")
        self.Menu_button.setGeometry(QRect(404, 622, 101, 31))
        self.Menu_button.setFont(font1)
        self.listWidget_menu = QListWidget(self.tab_5)
        self.listWidget_menu.setObjectName(u"listWidget_menu")
        self.listWidget_menu.setGeometry(QRect(0, 0, 961, 621))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setWeight(75)
        self.listWidget_menu.setFont(font4)
        self.tabWidget.addTab(self.tab_5, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.music_listWidget = QListWidget(self.tab_4)
        self.music_listWidget.setObjectName(u"music_listWidget")
        self.music_listWidget.setGeometry(QRect(80, 140, 311, 451))
        self.music_listWidget.setFont(font)
        self.label_3 = QLabel(self.tab_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 90, 91, 51))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(430, 140, 91, 51))
        self.label_4.setFont(font)
        self.label_7 = QLabel(self.tab_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(730, 30, 71, 71))
        self.label_7.setStyleSheet(u"image: url(:/Spider/novel_spider.svg);")
        self.layoutWidget1 = QWidget(self.tab_4)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(190, 30, 521, 81))
        self.layoutWidget1.setFont(font)
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.comboBox_music = QComboBox(self.layoutWidget1)
        self.comboBox_music.addItem("")
        self.comboBox_music.setObjectName(u"comboBox_music")
        self.comboBox_music.setFont(font)
        self.comboBox_music.setEditable(True)

        self.horizontalLayout_2.addWidget(self.comboBox_music)

        self.lineEdit_music = QLineEdit(self.layoutWidget1)
        self.lineEdit_music.setObjectName(u"lineEdit_music")
        self.lineEdit_music.setFont(font)

        self.horizontalLayout_2.addWidget(self.lineEdit_music)

        self.pushButton_music = QPushButton(self.layoutWidget1)
        self.pushButton_music.setObjectName(u"pushButton_music")
        self.pushButton_music.setFont(font)

        self.horizontalLayout_2.addWidget(self.pushButton_music)

        self.status_music_label = QLabel(self.tab_4)
        self.status_music_label.setObjectName(u"status_music_label")
        self.status_music_label.setGeometry(QRect(530, 140, 421, 51))
        self.status_music_label.setFont(font)
        self.tabWidget_2.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1164, 23))
        self.menuMENU = QMenu(self.menubar)
        self.menuMENU.setObjectName(u"menuMENU")
        font5 = QFont()
        font5.setPointSize(12)
        self.menuMENU.setFont(font5)
        self.menulayout = QMenu(self.menuMENU)
        self.menulayout.setObjectName(u"menulayout")
        self.menulayout.setFont(font4)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMENU.menuAction())
        self.menuMENU.addAction(self.actionclose)
        self.menuMENU.addAction(self.actionsave)
        self.menuMENU.addAction(self.actionwumaomao)
        self.menuMENU.addSeparator()
        self.menuMENU.addAction(self.menulayout.menuAction())
        self.menulayout.addAction(self.actionauthor)
        self.menulayout.addAction(self.actiongenre)
        self.menulayout.addAction(self.actionstatus)
        self.menulayout.addAction(self.actionname)
        self.menulayout.addAction(self.actionupdate_chapter)
        self.menulayout.addAction(self.actionintro)

        self.retranslateUi(MainWindow)

        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Spider System", None))
        self.actionclose.setText(QCoreApplication.translate("MainWindow", u"close", None))
#if QT_CONFIG(tooltip)
        self.actionclose.setToolTip(QCoreApplication.translate("MainWindow", u"close the exe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionclose.setStatusTip(QCoreApplication.translate("MainWindow", u"close the exe", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionclose.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionsave.setText(QCoreApplication.translate("MainWindow", u"save", None))
#if QT_CONFIG(tooltip)
        self.actionsave.setToolTip(QCoreApplication.translate("MainWindow", u"save", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionsave.setStatusTip(QCoreApplication.translate("MainWindow", u"save", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionsave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionwumaomao.setText(QCoreApplication.translate("MainWindow", u"wumaomao", None))
#if QT_CONFIG(tooltip)
        self.actionwumaomao.setToolTip(QCoreApplication.translate("MainWindow", u"should be handsome", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionwumaomao.setStatusTip(QCoreApplication.translate("MainWindow", u"should be handsome", None))
#endif // QT_CONFIG(statustip)
        self.actionauthor.setText(QCoreApplication.translate("MainWindow", u"author", None))
        self.actiongenre.setText(QCoreApplication.translate("MainWindow", u"genre", None))
        self.actionstatus.setText(QCoreApplication.translate("MainWindow", u"status", None))
        self.actionname.setText(QCoreApplication.translate("MainWindow", u"name", None))
        self.actionupdate_chapter.setText(QCoreApplication.translate("MainWindow", u"update_chapter", None))
        self.actionintro.setText(QCoreApplication.translate("MainWindow", u"intro", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"status:", None))
        self.state_label.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Result:", None))
#if QT_CONFIG(tooltip)
        self.book_list.setToolTip(QCoreApplication.translate("MainWindow", u"double clicked to download", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.book_list.setStatusTip(QCoreApplication.translate("MainWindow", u"double clicked to download", None))
#endif // QT_CONFIG(statustip)
        self.progressbar.setFormat("")
        self.label_8.setText("")
        self.search_push_button.setText(QCoreApplication.translate("MainWindow", u"Search", None))
#if QT_CONFIG(shortcut)
        self.search_push_button.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.book_name_label.setText(QCoreApplication.translate("MainWindow", u"KeyWord:", None))
        self.book_source_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7b14\u8da3\u9601", None))
        self.book_source_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u957f\u591c\u70fd\u706b", None))
        self.book_source_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u843d\u971e", None))

        self.source_label.setText(QCoreApplication.translate("MainWindow", u"Sources:", None))
#if QT_CONFIG(statustip)
        self.exit_novel_list.setStatusTip(QCoreApplication.translate("MainWindow", u"double clicked to download", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.novel_status_list.setStatusTip(QCoreApplication.translate("MainWindow", u"double click to load book", None))
#endif // QT_CONFIG(statustip)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Downloaded Files Lists", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"HOME", None))
#if QT_CONFIG(tooltip)
        self.rank_book_name_list.setToolTip(QCoreApplication.translate("MainWindow", u"double clicked", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.rank_book_name_list.setStatusTip(QCoreApplication.translate("MainWindow", u"double clicked", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.rank_author_list.setStatusTip(QCoreApplication.translate("MainWindow", u"double clicked to open the url", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.rank_genre_list.setStatusTip(QCoreApplication.translate("MainWindow", u"double clicked to open the url", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.rank_newest_chapter_list.setToolTip(QCoreApplication.translate("MainWindow", u"double clicked", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.rank_newest_chapter_list.setStatusTip(QCoreApplication.translate("MainWindow", u"double clicked", None))
#endif // QT_CONFIG(statustip)
        self.rank_label.setText(QCoreApplication.translate("MainWindow", u"checking ...", None))
        self.source_cobox.setItemText(0, QCoreApplication.translate("MainWindow", u"qidian", None))

#if QT_CONFIG(statustip)
        self.rank_button.setStatusTip(QCoreApplication.translate("MainWindow", u"click to get rank info", None))
#endif // QT_CONFIG(statustip)
        self.rank_button.setText(QCoreApplication.translate("MainWindow", u"Check", None))
#if QT_CONFIG(shortcut)
        self.rank_button.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.label_9.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"RANK", None))
#if QT_CONFIG(statustip)
        self.preview_button.setStatusTip(QCoreApplication.translate("MainWindow", u"last chapter", None))
#endif // QT_CONFIG(statustip)
        self.preview_button.setText(QCoreApplication.translate("MainWindow", u"Preview", None))
#if QT_CONFIG(statustip)
        self.Next_button.setStatusTip(QCoreApplication.translate("MainWindow", u"next chapter", None))
#endif // QT_CONFIG(statustip)
        self.Next_button.setText(QCoreApplication.translate("MainWindow", u"Next", None))
#if QT_CONFIG(statustip)
        self.Menu_button.setStatusTip(QCoreApplication.translate("MainWindow", u"Menu", None))
#endif // QT_CONFIG(statustip)
        self.Menu_button.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
#if QT_CONFIG(statustip)
        self.listWidget_menu.setStatusTip(QCoreApplication.translate("MainWindow", u"double click to change chapter", None))
#endif // QT_CONFIG(statustip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Browser", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u5c0f\u8bf4", None))
#if QT_CONFIG(statustip)
        self.music_listWidget.setStatusTip(QCoreApplication.translate("MainWindow", u"double clicked to download", None))
#endif // QT_CONFIG(statustip)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Result:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.label_7.setText("")
        self.comboBox_music.setItemText(0, QCoreApplication.translate("MainWindow", u"QQmusic", None))

        self.lineEdit_music.setText(QCoreApplication.translate("MainWindow", u"\u5468\u6770\u4f26", None))
        self.pushButton_music.setText(QCoreApplication.translate("MainWindow", u"Search", None))
#if QT_CONFIG(shortcut)
        self.pushButton_music.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.status_music_label.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u97f3\u4e50", None))
        self.menuMENU.setTitle(QCoreApplication.translate("MainWindow", u"MENU", None))
        self.menulayout.setTitle(QCoreApplication.translate("MainWindow", u"layout", None))
    # retranslateUi

